# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-27 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_auto_20171219_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ('creation_date',), 'permissions': (('can_change_status', '可改變狀態'),), 'verbose_name': 'newsletter', 'verbose_name_plural': 'newsletters'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='contentType',
            field=models.CharField(blank=True, choices=[(0, 'application/javascript (.js,.mjs)'), (1, 'application/json (.json)'), (2, 'application/msword (.doc,.dot,.wiz)'), (3, 'application/octet-stream (.bin,.a,.dll,.exe,.o,.obj,.so)'), (4, 'application/oda (.oda)'), (5, 'application/pdf (.pdf)'), (6, 'application/pkcs7-mime (.p7c)'), (7, 'application/postscript (.ps,.ai,.eps)'), (8, 'application/vnd.apple.mpegurl (.m3u,.m3u8)'), (9, 'application/vnd.ms-excel (.xls,.xlb)'), (10, 'application/vnd.ms-powerpoint (.ppt,.pot,.ppa,.pps,.pwz)'), (11, 'application/wasm (.wasm)'), (12, 'application/x-bcpio (.bcpio)'), (13, 'application/x-cpio (.cpio)'), (14, 'application/x-csh (.csh)'), (15, 'application/x-dvi (.dvi)'), (16, 'application/x-gtar (.gtar)'), (17, 'application/x-hdf (.hdf)'), (18, 'application/x-latex (.latex)'), (19, 'application/x-mif (.mif)'), (20, 'application/x-netcdf (.cdf,.nc)'), (21, 'application/x-pkcs12 (.p12,.pfx)'), (22, 'application/x-pn-realaudio (.ram)'), (23, 'application/x-python-code (.pyc,.pyo)'), (24, 'application/x-sh (.sh)'), (25, 'application/x-shar (.shar)'), (26, 'application/x-shockwave-flash (.swf)'), (27, 'application/x-sv4cpio (.sv4cpio)'), (28, 'application/x-sv4crc (.sv4crc)'), (29, 'application/x-tar (.tar)'), (30, 'application/x-tcl (.tcl)'), (31, 'application/x-tex (.tex)'), (32, 'application/x-texinfo (.texi,.texinfo)'), (33, 'application/x-troff (.roff,.t,.tr)'), (34, 'application/x-troff-man (.man)'), (35, 'application/x-troff-me (.me)'), (36, 'application/x-troff-ms (.ms)'), (37, 'application/x-ustar (.ustar)'), (38, 'application/x-wais-source (.src)'), (39, 'application/xml (.xsl,.rdf,.wsdl,.xpdl)'), (40, 'application/zip (.zip)'), (41, 'audio/basic (.au,.snd)'), (42, 'audio/mpeg (.mp3,.mp2)'), (43, 'audio/x-aiff (.aif,.aifc,.aiff)'), (44, 'audio/x-pn-realaudio (.ra)'), (45, 'audio/x-wav (.wav)'), (46, 'image/x-ms-bmp (.bmp)'), (47, 'image/gif (.gif)'), (48, 'image/ief (.ief)'), (49, 'image/jpeg (.jpg,.jpe,.jpeg)'), (50, 'image/png (.png)'), (51, 'image/svg+xml (.svg)'), (52, 'image/tiff (.tiff,.tif)'), (53, 'image/vnd.microsoft.icon (.ico)'), (54, 'image/x-cmu-raster (.ras)'), (55, 'image/x-portable-anymap (.pnm)'), (56, 'image/x-portable-bitmap (.pbm)'), (57, 'image/x-portable-graymap (.pgm)'), (58, 'image/x-portable-pixmap (.ppm)'), (59, 'image/x-rgb (.rgb)'), (60, 'image/x-xbitmap (.xbm)'), (61, 'image/x-xpixmap (.xpm)'), (62, 'image/x-xwindowdump (.xwd)'), (63, 'message/rfc822 (.eml,.mht,.mhtml,.nws)'), (64, 'text/css (.css)'), (65, 'text/csv (.csv)'), (66, 'text/html (.html,.htm)'), (67, 'text/plain (.txt,.bat,.c,.h,.ksh,.pl)'), (68, 'text/richtext (.rtx)'), (69, 'text/tab-separated-values (.tsv)'), (70, 'text/x-python (.py)'), (71, 'text/x-setext (.etx)'), (72, 'text/x-sgml (.sgm,.sgml)'), (73, 'text/x-vcard (.vcf)'), (74, 'text/xml (.xml)'), (75, 'video/mp4 (.mp4)'), (76, 'video/mpeg (.mpeg,.m1v,.mpa,.mpe,.mpg)'), (77, 'video/quicktime (.mov,.qt)'), (78, 'video/webm (.webm)'), (79, 'video/x-msvideo (.avi)'), (80, 'video/x-sgi-movie (.movie)')], max_length=255, verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='unsubscribers',
            field=models.ManyToManyField(blank=True, related_name='mailinglist_unsubscriber', to='newsletter.Contact', verbose_name='unsubscribers'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='content',
            field=models.TextField(default='<body>\n<!-- 在這裡編輯你的電子報 -->\n</body>', help_text='Or paste an URL.', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='header_reply',
            field=models.CharField(default='Emencia Newsletter<noreply@emencia.com>', max_length=255, verbose_name='reply to'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='header_sender',
            field=models.CharField(default='My NewsLetter <mq.nuwainfo.com>', max_length=255, verbose_name='sender'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='test_contacts',
            field=models.ManyToManyField(blank=True, to='newsletter.Contact', verbose_name='test contacts'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='newsletter.Contact', verbose_name='contacts'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='mailinglists',
            field=models.ManyToManyField(blank=True, to='newsletter.MailingList', verbose_name='mailing lists'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='newsletters',
            field=models.ManyToManyField(blank=True, to='newsletter.Newsletter', verbose_name='newsletters'),
        ),
    ]
